version: '2'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
      args:
            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    tty: true
    stdin_open: true
    environment:
      RAILS_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - .:/rails_app
    command: ["rails", "s", "-b", "0.0.0.0"]
